# =========================
# hooks on PRE-COMMIT
# =========================
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2
    hooks:
      - id: ruff
        name: ruff (lint)
        stages: [pre-commit]
        exclude: alembic/versions/.*

      - id: ruff-format
        name: ruff-format (format)
        stages: [pre-commit]
        exclude: alembic/versions/.*

  # =========================
  # hooks on PRE-PUSH
  # =========================
  - repo: local
    hooks:
      - id: mypy
        name: mypy (uv, on push)
        entry: uv run mypy
        language: system
        pass_filenames: false
        args: ["src"]
        stages: [pre-push]

  # =========================
  # hooks on COMMIT-MSG
  # =========================
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.9.1
    hooks:
      - id: commitizen
        stages: [commit-msg]
