services:
  app:
    image: fastapi-app:local
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./config.toml:/app/config.toml
    env_file:
      - ./.env
    environment:
      REDIS_URL: ${REDIS_URL}
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - minio
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]

  postgres:
    image: postgres:17.5-alpine
    container_name: postgres
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.0-alpine
    container_name: redis
    restart: always
    ports:
        - "6379:6379"
    volumes:
        - redis_data:/data

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    command: ["server", "/data", "--console-address", ":9001"]
    volumes:
      - minio-data:/data

volumes:
  minio-data:
  redis_data:
  postgres_data:


