"""init

Revision ID: 4d713db98f51
Revises:
Create Date: 2025-11-16 19:56:09.219366

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4d713db98f51"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "groups",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=11), nullable=False),
        sa.Column(
            "level_ed",
            sa.Enum(
                "BACHELOR",
                "DOCTORATE",
                "MASTER",
                "POSTGRADUATE",
                "SECONDARY_SPECIAL",
                "SPECIALIST",
                name="level_education",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "faculty",
            sa.Enum(
                "CYBERNETICS_AND_SECURITY",
                "DIGITAL_ECONOMY_AND_MEDIA",
                "INFORMATION_TECHNOLOGY",
                "NETWORKS_AND_COMMUNICATION",
                "RADIO_AND_TV",
                name="faculty",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("year_adm", sa.SmallInteger(), nullable=False),
        sa.Column("curator_id", sa.Uuid(), nullable=False),
        sa.Column("students_count", sa.SmallInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        # sa.ForeignKeyConstraint(['curator_id'], ['users.id'], ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("last_name", sa.String(length=35), nullable=False),
        sa.Column("first_name", sa.String(length=20), nullable=False),
        sa.Column("patronymic", sa.String(length=35), nullable=True),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column(
            "user_type",
            sa.Enum("CURATOR", "STUDENT", name="users_role", create_constraint=True),
            nullable=False,
        ),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column("group_id", sa.Uuid(), nullable=True),
        sa.Column("in_team", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        # sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_foreign_key(
        "fk_groups_curator_id_users",
        source_table="groups",
        referent_table="users",
        local_cols=["curator_id"],
        remote_cols=["id"],
        ondelete="RESTRICT",
    )

    op.create_foreign_key(
        "fk_users_group_id_groups",
        source_table="users",
        referent_table="groups",
        local_cols=["group_id"],
        remote_cols=["id"],
        ondelete="SET NULL",
    )

    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "projects",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("teamlead_id", sa.Uuid(), nullable=False),
        sa.Column("curator_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_completed", sa.Boolean(), nullable=False),
        sa.Column("github_url", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["curator_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["teamlead_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("file_url", sa.Text(), nullable=False),
        sa.Column("creator_id", sa.Uuid(), nullable=False),
        sa.Column("editor_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("teacher_note", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["creator_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["editor_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "Deadline",
                "NewInvite",
                "NewTask",
                "ProjectClosed",
                "RemoverFromProject",
                name="notification_type",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "projectreports",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("report_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["report_id"], ["reports.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("project_id", "report_id", name="pk_project_reports"),
    )
    op.create_table(
        "projectrole",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "Backend",
                "BusinessAnalyst",
                "Curator",
                "Devops",
                "Frontend",
                "Manager",
                "ProductManager",
                "TeamLead",
                name="team_role",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("project_id", "user_id", name="pk_project_role"),
    )
    op.create_table(
        "sprints",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("seq", sa.SmallInteger(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("goal", sa.String(length=100), nullable=True),
        sa.Column("start", sa.Date(), nullable=False),
        sa.Column("deadline", sa.Date(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "teams",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("Invited", "Member", "Owner", name="user_status", create_constraint=True),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "invitations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("notification_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("invited_user_id", sa.Uuid(), nullable=False),
        sa.Column("invited_by_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "Accepted", "Posted", "Rejected", name="invitation_status", create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["invited_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["invited_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["notification_id"],
            ["notifications.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("sprint_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column(
            "priority",
            sa.Enum("High", "Low", "Medium", name="task_priority", create_constraint=True),
            nullable=False,
        ),
        sa.Column(
            "tag",
            sa.Enum(
                "Backend",
                "BusinessAnalyst",
                "Curator",
                "Devops",
                "Frontend",
                "Manager",
                "ProductManager",
                "TeamLead",
                name="team_role",
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum("Done", "InProgress", "InReview", "InTest", "ToDo", name="taskstatus"),
            nullable=False,
        ),
        sa.Column("seq", sa.SmallInteger(), nullable=False),
        sa.Column("key", sa.String(length=32), nullable=False),
        sa.Column("deadline", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sprint_id"],
            ["sprints.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "performes",
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("assigne_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assigne_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("task_id", "assigne_id", name="pk_performes"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("performes")
    op.drop_table("tasks")
    op.drop_table("invitations")
    op.drop_table("teams")
    op.drop_table("sprints")
    op.drop_table("projectrole")
    op.drop_table("projectreports")
    op.drop_table("notifications")
    op.drop_table("reports")
    op.drop_table("projects")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("groups")
    # ### end Alembic commands ###
