"""indexing

Revision ID: 7fea9dc746f7
Revises: 4d713db98f51
Create Date: 2025-12-08 15:23:44.742053

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7fea9dc746f7"
down_revision: str | Sequence[str] | None = "4d713db98f51"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# enum-тип для статуса спринта
sprint_status_enum = sa.Enum(
    "UPCOMING",
    "ACTIVE",
    "COMPLETED",
    name="sprint_status",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "groups",
        "curator_id",
        existing_type=sa.UUID(),
        nullable=True,
    )
    op.create_index(
        op.f("ix_groups_curator_id"),
        "groups",
        ["curator_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("fk_groups_curator_id_users"),
        "groups",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "groups",
        "users",
        ["curator_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_index(
        op.f("ix_invitations_invited_by_id"),
        "invitations",
        ["invited_by_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_invitations_invited_user_id"),
        "invitations",
        ["invited_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_invitations_notification_id"),
        "invitations",
        ["notification_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_invitations_project_id"),
        "invitations",
        ["project_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("invitations_project_id_fkey"),
        "invitations",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("invitations_invited_by_id_fkey"),
        "invitations",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("invitations_invited_user_id_fkey"),
        "invitations",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("invitations_notification_id_fkey"),
        "invitations",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "invitations",
        "users",
        ["invited_by_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "invitations",
        "users",
        ["invited_user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "invitations",
        "notifications",
        ["notification_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "invitations",
        "projects",
        ["project_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(
        op.f("ix_notifications_project_id"),
        "notifications",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notifications_user_id"),
        "notifications",
        ["user_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("notifications_project_id_fkey"),
        "notifications",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("notifications_user_id_fkey"),
        "notifications",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "notifications",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "notifications",
        "projects",
        ["project_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(
        op.f("ix_performes_assigne_id"),
        "performes",
        ["assigne_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_performes_task_id"),
        "performes",
        ["task_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("performes_task_id_fkey"),
        "performes",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("performes_assigne_id_fkey"),
        "performes",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "performes",
        "users",
        ["assigne_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "performes",
        "tasks",
        ["task_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(
        op.f("ix_projectreports_project_id"),
        "projectreports",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_projectreports_report_id"),
        "projectreports",
        ["report_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_projectrole_project_id"),
        "projectrole",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_projectrole_user_id"),
        "projectrole",
        ["user_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("projectrole_user_id_fkey"),
        "projectrole",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("projectrole_project_id_fkey"),
        "projectrole",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "projectrole",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "projectrole",
        "projects",
        ["project_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(
        op.f("ix_projects_curator_id"),
        "projects",
        ["curator_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_projects_teamlead_id"),
        "projects",
        ["teamlead_id"],
        unique=False,
    )
    op.alter_column(
        "reports",
        "creator_id",
        existing_type=sa.UUID(),
        nullable=True,
    )
    op.drop_constraint(
        op.f("reports_creator_id_fkey"),
        "reports",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "reports",
        "users",
        ["creator_id"],
        ["id"],
        ondelete="SET NULL",
    )

    # --- sprint_status enum + колонка status ---

    # создаем тип ENUM в postgres (если его еще нет)
    sprint_status_enum.create(op.get_bind(), checkfirst=True)

    # добавляем колонку с временным server_default,
    # чтобы не упасть на NOT NULL, если в таблице уже есть строки
    op.add_column(
        "sprints",
        sa.Column(
            "status",
            sprint_status_enum,
            nullable=False,
            server_default="UPCOMING",
        ),
    )

    # убираем default на уровне БД, если он не нужен
    op.alter_column("sprints", "status", server_default=None)

    # --- остальные индексы / фк ---

    op.create_index(
        op.f("ix_sprints_project_id"),
        "sprints",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tasks_project_id"),
        "tasks",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tasks_sprint_id"),
        "tasks",
        ["sprint_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tasks_status"),
        "tasks",
        ["status"],
        unique=False,
    )
    op.drop_constraint(
        op.f("tasks_sprint_id_fkey"),
        "tasks",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("tasks_project_id_fkey"),
        "tasks",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "tasks",
        "sprints",
        ["sprint_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "tasks",
        "projects",
        ["project_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(
        op.f("ix_teams_project_id"),
        "teams",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_teams_user_id"),
        "teams",
        ["user_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("teams_user_id_fkey"),
        "teams",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("teams_project_id_fkey"),
        "teams",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "teams",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "teams",
        "projects",
        ["project_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(
        op.f("ix_users_group_id"),
        "users",
        ["group_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_group_id"), table_name="users")
    op.drop_constraint(None, "teams", type_="foreignkey")
    op.drop_constraint(None, "teams", type_="foreignkey")
    op.create_foreign_key(
        op.f("teams_project_id_fkey"),
        "teams",
        "projects",
        ["project_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("teams_user_id_fkey"),
        "teams",
        "users",
        ["user_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_teams_user_id"), table_name="teams")
    op.drop_index(op.f("ix_teams_project_id"), table_name="teams")
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.create_foreign_key(
        op.f("tasks_project_id_fkey"),
        "tasks",
        "projects",
        ["project_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("tasks_sprint_id_fkey"),
        "tasks",
        "sprints",
        ["sprint_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_tasks_status"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_sprint_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_project_id"), table_name="tasks")
    op.drop_index(op.f("ix_sprints_project_id"), table_name="sprints")

    # сначала удаляем колонку
    op.drop_column("sprints", "status")

    # потом дропаем enum-тип из postgres
    sprint_status_enum.drop(op.get_bind(), checkfirst=True)

    op.drop_constraint(None, "reports", type_="foreignkey")
    op.create_foreign_key(
        op.f("reports_creator_id_fkey"),
        "reports",
        "users",
        ["creator_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.alter_column(
        "reports",
        "creator_id",
        existing_type=sa.UUID(),
        nullable=False,
    )
    op.drop_index(op.f("ix_projects_teamlead_id"), table_name="projects")
    op.drop_index(op.f("ix_projects_curator_id"), table_name="projects")
    op.drop_constraint(None, "projectrole", type_="foreignkey")
    op.drop_constraint(None, "projectrole", type_="foreignkey")
    op.create_foreign_key(
        op.f("projectrole_project_id_fkey"),
        "projectrole",
        "projects",
        ["project_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("projectrole_user_id_fkey"),
        "projectrole",
        "users",
        ["user_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_projectrole_user_id"), table_name="projectrole")
    op.drop_index(op.f("ix_projectrole_project_id"), table_name="projectrole")
    op.drop_index(
        op.f("ix_projectreports_report_id"),
        table_name="projectreports",
    )
    op.drop_index(
        op.f("ix_projectreports_project_id"),
        table_name="projectreports",
    )
    op.drop_constraint(None, "performes", type_="foreignkey")
    op.drop_constraint(None, "performes", type_="foreignkey")
    op.create_foreign_key(
        op.f("performes_assigne_id_fkey"),
        "performes",
        "users",
        ["assigne_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("performes_task_id_fkey"),
        "performes",
        "tasks",
        ["task_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_performes_task_id"), table_name="performes")
    op.drop_index(op.f("ix_performes_assigne_id"), table_name="performes")
    op.drop_constraint(None, "notifications", type_="foreignkey")
    op.drop_constraint(None, "notifications", type_="foreignkey")
    op.create_foreign_key(
        op.f("notifications_user_id_fkey"),
        "notifications",
        "users",
        ["user_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("notifications_project_id_fkey"),
        "notifications",
        "projects",
        ["project_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_index(
        op.f("ix_notifications_project_id"),
        table_name="notifications",
    )
    op.drop_constraint(None, "invitations", type_="foreignkey")
    op.drop_constraint(None, "invitations", type_="foreignkey")
    op.drop_constraint(None, "invitations", type_="foreignkey")
    op.drop_constraint(None, "invitations", type_="foreignkey")
    op.create_foreign_key(
        op.f("invitations_notification_id_fkey"),
        "invitations",
        "notifications",
        ["notification_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("invitations_invited_user_id_fkey"),
        "invitations",
        "users",
        ["invited_user_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("invitations_invited_by_id_fkey"),
        "invitations",
        "users",
        ["invited_by_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("invitations_project_id_fkey"),
        "invitations",
        "projects",
        ["project_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_invitations_project_id"), table_name="invitations")
    op.drop_index(
        op.f("ix_invitations_notification_id"),
        table_name="invitations",
    )
    op.drop_index(
        op.f("ix_invitations_invited_user_id"),
        table_name="invitations",
    )
    op.drop_index(
        op.f("ix_invitations_invited_by_id"),
        table_name="invitations",
    )
    op.drop_constraint(None, "groups", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_groups_curator_id_users"),
        "groups",
        "users",
        ["curator_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_index(op.f("ix_groups_curator_id"), table_name="groups")
    op.alter_column(
        "groups",
        "curator_id",
        existing_type=sa.UUID(),
        nullable=False,
    )
    # ### end Alembic commands ###
