"""set on user.group_id nullable true

Revision ID: 8dfcee18765d
Revises: 7fea9dc746f7
Create Date: 2025-12-09 12:06:53.849579

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "8dfcee18765d"
down_revision: str | Sequence[str] | None = "7fea9dc746f7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
