"""fix

Revision ID: f8bbd85bbe10
Revises: 8dfcee18765d
Create Date: 2025-12-09 12:22:27.136199

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "f8bbd85bbe10"
down_revision: str | Sequence[str] | None = "8dfcee18765d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
