name: preview-release
on:
  pull_request:
    branches: [main]

jobs:
  dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: astral-sh/setup-uv@v3
      - run: uv sync --all-extras --dev
      - name: semantic-release dry run
        run: uv run semantic-release publish --noop
