name: release

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  release:
    if: github.event.repository.fork == false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch (not detached) with tags
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ github.ref_name }}
          persist-credentials: false  # <--- ВАЖНО: не подсовывать GITHUB_TOKEN

      - name: Configure git auth with PAT
        run: |
          git config user.name  "Release Bot"
          git config user.email "release-bot@teamforgepp.local"
          git remote set-url origin "https://x-access-token:${{ secrets.SEMANTIC_RELEASE_PAT }}@github.com/TeamForgePP/Backend.git"

      - name: Setup uv
        uses: astral-sh/setup-uv@v3

      - name: Sync deps
        run: uv sync --all-extras --dev

      - name: semantic-release version
        env:
          GH_TOKEN: ${{ secrets.SEMANTIC_RELEASE_PAT }}   # PAT для GitHub API
        run: uv run semantic-release version

      - name: semantic-release publish
        env:
          GH_TOKEN: ${{ secrets.SEMANTIC_RELEASE_PAT }}   # PAT для GitHub API
        run: uv run semantic-release publish
