name: release
on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  release:
    if: github.event.repository.fork == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: astral-sh/setup-uv@v3
      - run: uv sync --all-extras --dev
      - name: semantic-release
        run: uv run semantic-release publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
